viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
    db:
        host: !ENV ${DB_HOST}
        port: !ENV ${DB_PORT}
        dbname: !ENV ${DB_NAME}
        username: !ENV ${DB_USERNAME}
        password: !ENV ${DB_PASSWORD}
        table: !ENV ${DB_TABLE}
    mediahaven:
        id: !ENV ${MEDIAHAVEN_CLIENT_ID}
        secret: !ENV ${MEDIAHAVEN_CLIENT_SECRET}
        username: !ENV ${MEDIAHAVEN_USERNAME}
        password: !ENV ${MEDIAHAVEN_PASSWORD}
        url: !ENV ${MEDIAHAVEN_URL}
